library("ggplot2")

# read the values generated by the Device's computer
# Try to see a pattern.
vals <- read.delim("values.csv", sep=" ", header = FALSE)

show(vals)

ggplot(vals, aes(x=vals$V1, y=vals$V2)) + geom_line() + geom_point()

# see Rplots.pdf - seems that the function jumps all over the place, lika a pseudo-random generator.
# It doesn't seem to be a pattern (not at first glance) - so I'll leave the computer to execute until
# it finds a cycle.